baseURL = "https://www.poloxue.com/"
languageCode = "zh-cn"
title = "POLOXUE's BLOG"
theme = "ink-free"
copyright = "Polo Xue All rights reserved"

[taxonomies]
  tag = "tags"
  category = "categories"
  course = "courses"

[params]
  author = "POLO XUE"
  email = "poloxue123@gmail.com"
  avatar = "/avatar.png"
  description = "技术生活随笔记录"
  toc = "floating"
  wpm = 250
  maxTags = 7
	mode = "dark"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "POSTS"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "TAGS"
    url = "/tags"
    weight = 2
  [[menu.main]]
    identifier = "courses"
    name = "COURSES"
    url = "/courses"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about/"
    weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/poloxue/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/posts/index.xml"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
