baseURL = "https://www.poloxue.com/"
languageCode = "zh-cn"
title = "POLOXUE's BLOG"
copyright = "Polo Xue All rights reserved"

[modules]
[[module.imports]]
  path = "github.com/chollinger93/ink-free"

[taxonomies]
  tag = "tags"
  category = "categories"
  course = "courses"

[params]
  author = "POLO XUE"
  email = "poloxue123@gmail.com"
  avatar = "/avatar.png"
  description = "技术生活随笔记录"
  toc = "floating"
  wpm = 250
  maxTags = 7
	mode = "dark"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "文章列表"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "分类标签"
    url = "/tags"
    weight = 3
  # [[menu.main]]
  #   identifier = "courses"
  #   name = "系列课程"
  #   url = "/courses"
  #   weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 6

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/poloxue/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/posts/index.xml"

[[params.social]]
name = "Wechat"
icon = "message-circle"
url = "/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
