baseURL = "https://www.poloxue.com/"
defaultContentLanguage = "zh-cn"
title = "菠萝学量化"
copyright = "Polo Xue All rights reserved"

enableRobotsTXT = true
summaryLength = 0
hasCJKLanguage = true
enableEmoji = true
enableGitInfo = true

[pagination]
  pagerSize = 9

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 100

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = true
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['\\(', '\\)']]

[params]
  [params.Author]
    name = "POLO XUE"
    image = "avatar.png"
    email = "poloxue123@gmail.com"
    headline = "交易者 · 开发者"
    bio = "专注量化交易与技术分析"
    links = [
      { github = "https://github.com/poloxue/" },
    ]

[languages]
  [languages.zh-cn]
    label = "中文"
    locale = "zh-cn"
    contentDir = "content"
    weight = 1
    title = "菠萝学量化"
    [languages.zh-cn.params]
      dateFormat = "2006-01-02"
      displayName = "中文"
      isoCode = "zh-cn"
      description = "技术、交易与量化"