baseURL = "https://www.poloxue.com"
languageCode = "zh-cn"
title = "POLOXUE's 博客频道"
theme = "ink-free"
copyright = "2023 Polo Xue All rights reserved"


[params]
  author = "POLO XUE"
  email = "poloxue123@gmail.com"
  avatar = "/avatar.webp"
  description = "技术生活随笔记录"
  menu_item_separator = "<br/>"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "coder"
    name = "编程杂谈"
    url = "/posts/coder"
    weight = 2
  [[menu.main]]
    identifier = "trader"
    name = "交易人生"
    url = "/posts/trader"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 4
